name: Auto Request Review

on:
  pull_request:
    branches:
    - main
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: sachie-swapcardian/sach-auto-review@v0.1.0
        with:
          token: ${{ secrets.PAT }}
          config: .github/auto_request_review.yml
